login() ::= <<
<!DOCTYPE html>
<html>
<head>
    <center>
        <table border="0" cellspacing="0" cellpadding="0">
        </table>
    </center>
    <title>login</title>
<body>
<body>
<fieldset style="margin:0% 10% 10% 10%">
    <form name="login" method="post" action="login">
        <p><font size="+1" face="abc" color="#0066FF"><b>Welcome to Dmail</b></font><hr /></p>
        <center>
            <table border="0">
                <tr>
                    <td width="91" align="right">username<font color="#FF0000"></font></td>
                    <td width="296" align="left"><input type="text" name="username" size="22" ></td>
                </tr>
                <tr>
                    <td align="right">password<font color="#FF0000"></font></td>
                    <td align="left"><input name="password" type="password" size="22"></td>
                </tr>
            </table>
        </center>
        </center></p>
        <center>
            <table  border="0">
                <tr>
                    <td width="243" align="left" nowrap>
                        <font size="+5"><strong>
                            <input name="login" type="submit" value="login">
                            <input name="register" type="button" value="register" onclick="javascript:window.location.href='register.html'">
                        </strong></font></h1></td>
                </tr>
            </table>
        </center>
    </form>
</fieldset>
</body>
</body>
</html>
>>